### PR TITLE
Copying assets for VS2017

### PR DESCRIPTION
**Pull request by imrahul361**
for the issue #9

### CODE REVIEW

**Comment by Roshanjossey** [comment]
Hi @imrahul361, I see that you've added all the assets in assets folder to  gui-tool-tutorials/github-windows-vs2017-tutorial/ directory. We only want files used in visual studio tutorial in there.

**Comment by imrahul361** [comment]
@Roshanjossey  do you mean only file named vscode2017*.png?

**Comment by Roshanjossey** [comment]
Yeah.

**Comment by imrahul361** [comment]
check now @Roshanjossey

**Comment by Roshanjossey** [comment]
Cool cool cool

**Pull request merged**
