### PR TITLE
Update copy-to-clipboard image in Readme

### PR DESCRIPTION
**Pull request by codekakitai51**
fix for the issue https://github.com/firstcontributions/first-contributions/issues/87898

### CODE REVIEW

**Review by Roshanjossey — CHANGES_REQUESTED** [review]
Thank you for this change, could you please crop a little more so it's close to the size of previous one and add a shadow  similar to the previous one?

image

**Comment by codekakitai51** [comment]
Hi, @Roshanjossey,

> could you please crop a little more so it's close to the size of previous one and add a shadow similar to the previous one?

Done with this. Please confirm it.

**Comment by Roshanjossey** [comment]
Could you make the background transparent like the previous one?

**Comment by codekakitai51** [comment]
@Roshanjossey,
Done with making bg transparent. Please check it.

**Pull request merged**
