### PR TITLE
Added the remainder of the assets.

### PR DESCRIPTION
**Pull request by SPOCTONE**
linked to issue #2

### CODE REVIEW

**Comment by Roshanjossey** [comment]
@SPOCTONE, we don't want all the assets in Readme directory. It'll be better to structure it to their own directories. 

Please remove files other than the ones used in main Readme.md

**Comment by SPOCTONE** [comment]
all right. on it.

**Comment by SPOCTONE** [comment]
done with the changes. please check.

**Comment by Roshanjossey** [comment]
Awesome. Thank you for making these changes

**Pull request merged**
